# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Marraqueta
                                 A QGIS plugin
 Ponders different rasters with different utility functions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-14
        git sha              : $Format:%H$
        copyright            : (C) 2024 by fdobad@github
        email                : fbadilla@ing.uchile.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import tempfile

import numpy as np
from fire2a.raster import read_raster
from osgeo import gdal
from qgis.core import Qgis, QgsMessageLog
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Import the code for the dialog
from .pan_batido_dialog import MarraquetaDialog
# Initialize Qt resources from file resources.py
from .resources.resources import *


class Marraqueta:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", "Marraqueta_{}.qm".format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Pan Europeo")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("Marraqueta", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/pan_batido/resources/marraqueta.svg"
        self.add_action(
            icon_path, text=self.tr("Load rasters before launching!"), callback=self.run, parent=self.iface.mainWindow()
        )

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&Pan Europeo"), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""
        QgsMessageLog.logMessage(f"current layers {self.iface.mapCanvas().layers()}", "Marraqueta", Qgis.Info)

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            if len(self.iface.mapCanvas().layers()) == 0:
                QgsMessageLog.logMessage("No layers loaded. Not loading the dialog!", "Marraqueta", Qgis.Critical)
                # display a message in system toolbar
                self.iface.messageBar().pushMessage(
                    "No layers loaded",
                    "Please load some raster layers before launching the PAN-BATIDO plugin",
                    level=Qgis.Critical,
                    duration=5,
                )
                return
            self.first_start = False
            self.dlg = MarraquetaDialog()
            self.lyr_data = []
            for dlg_row in self.dlg.rows:
                layer = dlg_row["layer"]
                dat, info = read_raster(layer.publicSource())
                self.lyr_data += [{"layer": layer, "data": dat, "info": info}]
                rimin, rimax = int(np.floor(info["Minimum"])), int(np.ceil(info["Maximum"]))
                QgsMessageLog.logMessage(f"{rimin=} {rimax=}", "Marraqueta", Qgis.Info)
                for name in ["a_spinbox", "b_spinbox", "a_slider", "b_slider"]:
                    ret_val = dlg_row[name].setRange(rimin, rimax)
                    QgsMessageLog.logMessage(f"{name=} {ret_val=}", "Marraqueta", Qgis.Info)
            QgsMessageLog.logMessage(f"{self.lyr_data=}", "Marraqueta", Qgis.Info)
            self.H, self.W = self.lyr_data[0]["data"].shape
            self.GT = self.lyr_data[0]["info"]["Transform"]
            self.crs_auth_id = self.lyr_data[0]["layer"].crs().authid()
            QgsMessageLog.logMessage(
                f"H:{self.H} W:{self.W} GeoTransform:{self.GT} crs-auth-id:{self.crs_auth_id}", "Marraqueta", Qgis.Info
            )
            QgsMessageLog.logMessage("not checking if rasters match!", "Marraqueta", Qgis.Warning)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        QgsMessageLog.logMessage(f"{result=} {self.dlg.DialogCode()=}", "Marraqueta", Qgis.Info)
        # See if OK was pressed
        if result:
            QgsMessageLog.logMessage("OK clicked", "Marraqueta", Qgis.Info)

            self.dlg.rescale_weights()

            final_data = np.zeros((self.H, self.W), dtype=np.float32)
            did_any = False
            for dlg_row in self.dlg.rows:
                if dlg_row["weight_checkbox"].isChecked() and dlg_row["weight_spinbox"].value() != 0:
                    weight = dlg_row["weight_spinbox"].value()
                    lyr = self.lyr_data[dlg_row["i"]]
                    lyr_data = lyr["data"]
                    lyr_nodata = lyr["info"]["NoDataValue"]
                    match dlg_row["func_dropdown"].currentIndex():
                        case 0:
                            new_data = min_max_scaling(
                                lyr_data, lyr_nodata, invert=dlg_row["minmax_invert"].isChecked()
                            )
                            did_any = True
                        case 1:
                            a = dlg_row["a_spinbox"].value()
                            b = dlg_row["b_spinbox"].value()
                            if a != b:
                                new_data = bi_piecewise_linear(
                                    lyr_data, lyr_nodata, dlg_row["a_spinbox"].value(), dlg_row["b_spinbox"].value()
                                )
                                did_any = True
                    QgsMessageLog.logMessage(
                        f"{lyr['layer'].name()=} {np.histogram(new_data)=}", "Marraqueta", Qgis.Info
                    )
                    final_data[lyr_data != lyr_nodata] += weight / 100 * new_data[lyr_data != lyr_nodata]

            if not did_any:
                QgsMessageLog.logMessage("Nothing to do, all layers unselected or 0 weight", "Marraqueta", Qgis.Info)
                return

            # create a new layer with final data
            afile = tempfile.mktemp(suffix=".tif")
            ds = gdal.GetDriverByName("GTiff").Create(afile, self.W, self.H, 1, gdal.GDT_Float32)
            ds.SetGeoTransform(self.GT)  # specify coords
            ds.SetProjection(self.crs_auth_id)  # export coords to file
            band = ds.GetRasterBand(1)
            if 0 != band.SetNoDataValue(-9999):
                QgsMessageLog.logMessage("Set No Data failed", "Marraqueta", Qgis.Critical)
            if 0 != band.WriteArray(final_data):
                QgsMessageLog.logMessage("WriteArray failed", "Marraqueta", Qgis.Critical)
            ds.FlushCache()  # write to disk
            ds = None

            # add the raster layer to the canvas
            self.iface.addRasterLayer(afile, "final_data")


def min_max_scaling(data, nodata, invert=False):
    min_val = data[data != nodata].min()
    max_val = data[data != nodata].max()
    if max_val != min_val:
        ret_val = (data - min_val) / (max_val - min_val)
        if invert:
            return np.float32(1 - ret_val)
        return np.float32(ret_val)
    else:
        return np.zeros_like(data, dtype=np.float32)


def bi_piecewise_linear(data, nodata, a, b):
    ret_val = np.empty_like(data, dtype=np.float32)
    ret_val[data != nodata] = (data[data != nodata] - a) / (b - a)
    ret_val[data == nodata] = data[data == nodata]
    return np.float32(ret_val)
