# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProcessingClassName
                                 A QGIS plugin
 This is the plugin description.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-18
        copyright            : (C) 2025 by fdobad
        email                : fbadilla@ing.uchile.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "fdobad"
__date__ = "2025-02-18"
__copyright__ = "(C) 2025 by fdobad"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProcessingClassName class from file ProcessingClassName.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .panettone import Panettone

    return Panettone()
