name: Create Release for Dialog

on:
  push:
    tags:
      - 'dialog-v[0-9]+.[0-9]+.[0-9]+\w?'
      - 'v[0-9]+.[0-9]+.[0-9]+\w?'
  workflow_dispatch:
  pull_request:

jobs:
  archive-n-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Resolve symbolic links
      run: |
        chmod +x resolve_symlinks.sh
        ./resolve_symlinks.sh

    - name: Set version and tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "RELEASE_TAG=PullRequest" >> $GITHUB_ENV
          echo "TAG_DESCRIPTION=PullRequest${{ github.event.pull_request.number}}" >> $GITHUB_ENV
          VERSION="0.0.0"
        else
          echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          TAG_NAME=$(git describe --tags)
          echo "TAG_DESCRIPTION=$(git tag -n99 $TAG_NAME | sed -n '2p')" >> $GITHUB_ENV
          VERSION=$(echo $RELEASE_TAG | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Version bump
      run: |
        VERSION=${{ env.VERSION }}
        sed -i -e "s/version=0.0.1/version=${VERSION}/" pan_batido/metadata.txt

    - name: Archive fire2a-lib
      run: |
        git add pan_batido/metadata.txt
        stash=`git stash create`
        git archive --output "pan_batido_$VERSION.zip" $stash pan_batido

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "pan_batido_${{ env.VERSION }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        tag: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_TAG }}
        body: ${{ env.TAG_DESCRIPTION }}
        allowUpdates: true
        updateOnlyUnreleased: true
