name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Release Tag
      id: set_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "RELEASE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "TAG_DESCRIPTION=${{ github.sha }}" >> $GITHUB_ENV
        else
          echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          TAG_NAME=$(git describe --tags)
          echo "TAG_DESCRIPTION=$(git tag -n99 $TAG_NAME | sed -n '2p')" >> $GITHUB_ENV
        fi

    - name: Version bump
      run: |
         VERSION=${{ env.RELEASE_TAG }}
         echo "version is ${VERSION}"
         sed -i -e "s/version=0.0.1/version=${VERSION}/" pan_batido/metadata.txt
         git add pan_batido/metadata.txt

    - name: Checkout fire2a-lib
      uses: actions/checkout@v2
      with:
        repository: "fire2a/fire2a-lib" 
        path: "fire2a"
        sparse-checkout: |
          src/fire2a/raster/*
          src/fire2a/utils.py
        sparse-checkout-cone-mode: false

    - name: git archive
      run: |
         echo "Changing fire2a from installed to relative import"
         mv fire2a/src/fire2a pan_batido/.
         # rm -rf fire2a
         grep -Rl --include=*py "from fire2a" | tee will.change | xargs -I {} sed -i "s/^from fire2a/from .fire2a/" {}
         echo "Changed files"
         cat will.change 
         # rm will.change

         git add pan_batido/fire2a
         lestash=`git stash create`

         git archive --output "pan_batido_${{ env.RELEASE_TAG }}.zip" $lestash pan_batido

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "pan_batido_${{ env.RELEASE_TAG }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        name: ${{ env.RELEASE_TAG }}
        body: ${{ env.TAG_DESCRIPTION }}
