---
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          git config --global user.name 'Fdo Bad Vel'
          git config --global user.email 'fbadilla@ing.uchile.cl'
          git init -b gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/fire2a/qgis-pan-europeo.git gh-pages
